import type { CashBuyer, Campaign, MarketSuggestion, Market } from './types'

export const MARKET_SUGGESTIONS: MarketSuggestion[] = [
  { name: 'Atlanta', state: 'GA', type: 'city', estimatedBuyers: 847 },
  { name: 'Fulton County', state: 'GA', type: 'county', estimatedBuyers: 1204 },
  { name: 'Charlotte', state: 'NC', type: 'city', estimatedBuyers: 612 },
  { name: 'Mecklenburg County', state: 'NC', type: 'county', estimatedBuyers: 734 },
  { name: 'Tampa', state: 'FL', type: 'city', estimatedBuyers: 921 },
  { name: 'Hillsborough County', state: 'FL', type: 'county', estimatedBuyers: 1089 },
  { name: 'Dallas', state: 'TX', type: 'city', estimatedBuyers: 1432 },
  { name: 'Dallas County', state: 'TX', type: 'county', estimatedBuyers: 1876 },
  { name: 'Phoenix', state: 'AZ', type: 'city', estimatedBuyers: 1108 },
  { name: 'Maricopa County', state: 'AZ', type: 'county', estimatedBuyers: 2341 },
  { name: 'Memphis', state: 'TN', type: 'city', estimatedBuyers: 438 },
  { name: 'Shelby County', state: 'TN', type: 'county', estimatedBuyers: 521 },
  { name: 'Jacksonville', state: 'FL', type: 'city', estimatedBuyers: 567 },
  { name: 'Columbus', state: 'OH', type: 'city', estimatedBuyers: 489 },
  { name: 'Indianapolis', state: 'IN', type: 'city', estimatedBuyers: 403 },
  { name: 'Kansas City', state: 'MO', type: 'city', estimatedBuyers: 374 },
  { name: 'Birmingham', state: 'AL', type: 'city', estimatedBuyers: 298 },
  { name: '30301', state: 'GA', type: 'zip', estimatedBuyers: 124 },
  { name: '30310', state: 'GA', type: 'zip', estimatedBuyers: 89 },
  { name: '28202', state: 'NC', type: 'zip', estimatedBuyers: 67 },
]

export const MOCK_BUYERS: CashBuyer[] = [
  {
    id: '1',
    name: 'Heritage Capital Holdings LLC',
    entityType: 'llc',
    phone: '(404) 555-0182',
    email: 'acquisitions@heritagecapitalatl.com',
    mailingAddress: '1420 Peachtree St NE, Atlanta, GA 30309',
    cashPurchases12mo: 14,
    lastPurchaseDate: '2024-11-28',
    priceRangeMin: 80000,
    priceRangeMax: 220000,
    propertyTypes: ['sfr', 'multi'],
    contactStatus: 'enriched',
    activityScore: 94,
    inCRM: true,
  },
  {
    id: '2',
    name: 'Marcus D. Williams',
    entityType: 'individual',
    phone: '(404) 555-0247',
    cashPurchases12mo: 8,
    lastPurchaseDate: '2024-12-04',
    priceRangeMin: 120000,
    priceRangeMax: 185000,
    propertyTypes: ['sfr'],
    contactStatus: 'enriched',
    activityScore: 88,
    inCRM: false,
  },
  {
    id: '3',
    name: 'Southeastern Property Group LLC',
    entityType: 'llc',
    phone: '(770) 555-0391',
    email: 'deals@sepgroup.io',
    mailingAddress: '300 Galleria Pkwy SE, Atlanta, GA 30339',
    cashPurchases12mo: 22,
    lastPurchaseDate: '2024-12-10',
    priceRangeMin: 60000,
    priceRangeMax: 310000,
    propertyTypes: ['sfr', 'commercial'],
    contactStatus: 'enriched',
    activityScore: 97,
    inCRM: false,
  },
  {
    id: '4',
    name: 'Robert & Patricia Chen Trust',
    entityType: 'trust',
    cashPurchases12mo: 5,
    lastPurchaseDate: '2024-10-17',
    priceRangeMin: 200000,
    priceRangeMax: 460000,
    propertyTypes: ['multi', 'commercial'],
    contactStatus: 'needs_enrichment',
    activityScore: 71,
    inCRM: false,
  },
  {
    id: '5',
    name: 'ATL Fast Close LLC',
    entityType: 'llc',
    phone: '(678) 555-0518',
    cashPurchases12mo: 31,
    lastPurchaseDate: '2024-12-08',
    priceRangeMin: 45000,
    priceRangeMax: 165000,
    propertyTypes: ['sfr'],
    contactStatus: 'enriched',
    activityScore: 99,
    inCRM: true,
  },
  {
    id: '6',
    name: 'Darnell L. Johnson',
    entityType: 'individual',
    cashPurchases12mo: 3,
    lastPurchaseDate: '2024-09-22',
    priceRangeMin: 90000,
    priceRangeMax: 145000,
    propertyTypes: ['sfr'],
    contactStatus: 'needs_enrichment',
    activityScore: 58,
    inCRM: false,
  },
  {
    id: '7',
    name: 'BlueStar Acquisitions Corp',
    entityType: 'corporation',
    phone: '(404) 555-0764',
    email: 'invest@bluestarholdings.com',
    cashPurchases12mo: 19,
    lastPurchaseDate: '2024-11-30',
    priceRangeMin: 150000,
    priceRangeMax: 520000,
    propertyTypes: ['multi', 'commercial'],
    contactStatus: 'enriched',
    activityScore: 92,
    inCRM: false,
  },
  {
    id: '8',
    name: 'KeyCity Investors LLC',
    entityType: 'llc',
    phone: '(404) 555-0833',
    cashPurchases12mo: 11,
    lastPurchaseDate: '2024-11-15',
    priceRangeMin: 70000,
    priceRangeMax: 200000,
    propertyTypes: ['sfr', 'multi'],
    contactStatus: 'enriched',
    activityScore: 84,
    inCRM: false,
  },
  {
    id: '9',
    name: 'Sandra G. Morales',
    entityType: 'individual',
    cashPurchases12mo: 6,
    lastPurchaseDate: '2024-10-29',
    priceRangeMin: 80000,
    priceRangeMax: 160000,
    propertyTypes: ['sfr'],
    contactStatus: 'needs_enrichment',
    activityScore: 74,
    inCRM: false,
  },
  {
    id: '10',
    name: 'Fulton Peak Properties LLC',
    entityType: 'llc',
    phone: '(770) 555-0972',
    email: 'buy@fultonpeak.com',
    cashPurchases12mo: 27,
    lastPurchaseDate: '2024-12-11',
    priceRangeMin: 55000,
    priceRangeMax: 255000,
    propertyTypes: ['sfr'],
    contactStatus: 'enriched',
    activityScore: 98,
    inCRM: true,
  },
  {
    id: '11',
    name: 'Michael T. Robinson',
    entityType: 'individual',
    phone: '(678) 555-1047',
    cashPurchases12mo: 4,
    lastPurchaseDate: '2024-11-02',
    priceRangeMin: 110000,
    priceRangeMax: 195000,
    propertyTypes: ['sfr'],
    contactStatus: 'enriched',
    activityScore: 66,
    inCRM: false,
  },
  {
    id: '12',
    name: 'Crown Capital Real Estate Corp',
    entityType: 'corporation',
    phone: '(404) 555-1198',
    email: 'deals@crowncapitalre.com',
    cashPurchases12mo: 9,
    lastPurchaseDate: '2024-10-08',
    priceRangeMin: 250000,
    priceRangeMax: 800000,
    propertyTypes: ['multi', 'commercial'],
    contactStatus: 'enriched',
    activityScore: 62,
    inCRM: false,
  },
  {
    id: '13',
    name: 'Peach State Realty Ventures LLC',
    entityType: 'llc',
    cashPurchases12mo: 16,
    lastPurchaseDate: '2024-11-20',
    priceRangeMin: 65000,
    priceRangeMax: 180000,
    propertyTypes: ['sfr', 'multi'],
    contactStatus: 'needs_enrichment',
    activityScore: 89,
    inCRM: false,
  },
  {
    id: '14',
    name: 'Jerome & Keisha Williams',
    entityType: 'individual',
    cashPurchases12mo: 2,
    lastPurchaseDate: '2024-08-14',
    priceRangeMin: 95000,
    priceRangeMax: 155000,
    propertyTypes: ['sfr'],
    contactStatus: 'do_not_call',
    activityScore: 41,
    inCRM: false,
  },
  {
    id: '15',
    name: 'Momentum REI Group LLC',
    entityType: 'llc',
    phone: '(404) 555-1334',
    cashPurchases12mo: 18,
    lastPurchaseDate: '2024-12-03',
    priceRangeMin: 70000,
    priceRangeMax: 240000,
    propertyTypes: ['sfr', 'multi'],
    contactStatus: 'enriched',
    activityScore: 91,
    inCRM: false,
  },
]

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'c1',
    name: 'Q4 Buyer Refresh — Atlanta',
    marketName: 'Atlanta, GA',
    buyerSource: 'discovery',
    buyerCount: 42,
    scriptTemplate: 'standard',
    companyName: 'Pinnacle Home Buyers',
    agentName: 'Sarah',
    tone: 'professional',
    mode: 'ai',
    maxConcurrent: 5,
    callHoursStart: '09:00',
    callHoursEnd: '19:00',
    voicemailAction: 'leave_message',
    retryCount: 2,
    retryHours: 4,
    scheduleType: 'now',
    complianceAgreed: true,
    status: 'completed',
    buyersTotal: 42,
    buyersCalled: 42,
    callsQualified: 13,
    callsNotBuying: 18,
    callsNoAnswer: 11,
    totalTalkSeconds: 7420,
    startedAt: '2024-12-01T10:00:00Z',
    completedAt: '2024-12-01T14:22:00Z',
    createdAt: '2024-12-01T09:45:00Z',
  },
  {
    id: 'c2',
    name: 'New Market Intro — Fulton County',
    marketName: 'Fulton County, GA',
    buyerSource: 'discovery',
    buyerCount: 67,
    scriptTemplate: 'new_market',
    companyName: 'Pinnacle Home Buyers',
    agentName: 'Marcus',
    tone: 'conversational',
    mode: 'ai',
    maxConcurrent: 8,
    callHoursStart: '09:00',
    callHoursEnd: '19:00',
    voicemailAction: 'hang_up',
    retryCount: 1,
    retryHours: 6,
    scheduleType: 'now',
    complianceAgreed: true,
    status: 'completed',
    buyersTotal: 67,
    buyersCalled: 67,
    callsQualified: 16,
    callsNotBuying: 29,
    callsNoAnswer: 22,
    totalTalkSeconds: 11840,
    startedAt: '2024-11-18T09:00:00Z',
    completedAt: '2024-11-18T16:45:00Z',
    createdAt: '2024-11-17T17:00:00Z',
  },
  {
    id: 'c3',
    name: 'Deal-Specific: 847 Oak Park Dr',
    marketName: 'Atlanta, GA',
    buyerSource: 'crm',
    buyerCount: 18,
    scriptTemplate: 'deal_specific',
    companyName: 'Pinnacle Home Buyers',
    agentName: 'Sarah',
    tone: 'professional',
    mode: 'ai',
    maxConcurrent: 3,
    callHoursStart: '10:00',
    callHoursEnd: '18:00',
    voicemailAction: 'leave_message',
    retryCount: 2,
    retryHours: 3,
    scheduleType: 'now',
    complianceAgreed: true,
    status: 'completed',
    buyersTotal: 18,
    buyersCalled: 18,
    callsQualified: 8,
    callsNotBuying: 6,
    callsNoAnswer: 4,
    totalTalkSeconds: 3960,
    startedAt: '2024-11-05T11:00:00Z',
    completedAt: '2024-11-05T13:10:00Z',
    createdAt: '2024-11-05T10:30:00Z',
  },
  {
    id: 'c4',
    name: 'Dormant Buyer Re-engagement',
    marketName: 'Atlanta, GA',
    buyerSource: 'crm',
    buyerCount: 34,
    scriptTemplate: 'checkin',
    companyName: 'Pinnacle Home Buyers',
    agentName: 'Marcus',
    tone: 'conversational',
    mode: 'ai',
    maxConcurrent: 5,
    callHoursStart: '09:00',
    callHoursEnd: '19:00',
    voicemailAction: 'leave_message',
    retryCount: 1,
    retryHours: 24,
    scheduleType: 'now',
    complianceAgreed: true,
    status: 'paused',
    buyersTotal: 34,
    buyersCalled: 19,
    callsQualified: 5,
    callsNotBuying: 8,
    callsNoAnswer: 6,
    totalTalkSeconds: 3280,
    startedAt: '2024-12-09T09:00:00Z',
    createdAt: '2024-12-08T16:00:00Z',
  },
]

export const PREVIOUS_MARKETS: Market[] = [
  { id: 'm1', name: 'Atlanta', type: 'city', state: 'GA', buyerCount: 847, lastSynced: '2024-12-08T14:00:00Z' },
  { id: 'm2', name: 'Fulton County', type: 'county', state: 'GA', buyerCount: 1204, lastSynced: '2024-11-18T09:00:00Z' },
]

export const SCRIPT_TEMPLATES = [
  {
    id: 'standard',
    name: 'Standard Buyer Qualification',
    description: 'Find out if they\'re still buying, capture preferences and price range',
    preview: `"Hi [Name], this is [Agent] calling from [Company]. I saw you've been active buying properties in [Market] — are you still looking to add to your portfolio? ... Great, what types of properties are you focusing on and what's your typical price range?"`,
    avgDuration: '2-4 min',
    qualifyRate: '28%',
  },
  {
    id: 'checkin',
    name: 'Quick Check-In',
    description: 'Short re-engagement call for buyers you\'ve spoken with before',
    preview: `"Hey [Name], [Agent] here from [Company]. We connected a while back — just checking in to see if you're still in the market. We've got some new inventory coming in [Market] that I think you'd like."`,
    avgDuration: '1-2 min',
    qualifyRate: '34%',
  },
  {
    id: 'new_market',
    name: 'New Market Introduction',
    description: 'Introduce your company to buyers in a market you\'re new to',
    preview: `"Hi [Name], this is [Agent] with [Company]. We just started working deals in [Market] and we're building our buyer network here. I saw you've been active in this area — would you be interested in off-market deals sent directly to you?"`,
    avgDuration: '2-3 min',
    qualifyRate: '22%',
  },
  {
    id: 'deal_specific',
    name: 'Deal-Specific Outreach',
    description: 'Pitch a specific property you have under contract',
    preview: `"Hi [Name], [Agent] calling from [Company]. I have an off-market property I think you'd love — it's a [Property Type] in [Neighborhood], priced at [Price]. Based on what you've been buying, it looks right in your wheelhouse. Do you have 90 seconds?"`,
    avgDuration: '3-5 min',
    qualifyRate: '41%',
  },
]

// Simulated live transcript for demo
export const DEMO_TRANSCRIPT = [
  { speaker: 'agent' as const, text: "Hi, this is Sarah calling from Pinnacle Home Buyers. Am I speaking with Marcus Williams?", timestamp: 0 },
  { speaker: 'buyer' as const, text: "Yeah, this is Marcus. Who's this?", timestamp: 4 },
  { speaker: 'agent' as const, text: "Hi Marcus! I'm with Pinnacle Home Buyers — we're a local real estate investment company. I saw you've been active buying properties in the Atlanta area. Do you have a quick minute?", timestamp: 7 },
  { speaker: 'buyer' as const, text: "Sure, what's this about?", timestamp: 15 },
  { speaker: 'agent' as const, text: "We work with wholesalers across Atlanta and we're always looking to connect with active buyers. Are you still looking to purchase investment properties?", timestamp: 18 },
  { speaker: 'buyer' as const, text: "Yeah I'm always looking. What kind of deals do you have?", timestamp: 27 },
  { speaker: 'agent' as const, text: "We specialize in off-market SFRs and small multis in the Atlanta metro. What's your typical price range?", timestamp: 32 },
  { speaker: 'buyer' as const, text: "I'm usually in the 100 to 180 range for single family. Has to be in a decent area though.", timestamp: 40 },
  { speaker: 'agent' as const, text: "Perfect — that's right in our wheelhouse. Are you looking to flip or hold long term?", timestamp: 50 },
  { speaker: 'buyer' as const, text: "Mix of both, depends on the numbers.", timestamp: 56 },
  { speaker: 'agent' as const, text: "Got it. And how quickly can you close if the numbers work?", timestamp: 60 },
  { speaker: 'buyer' as const, text: "I can close in 10 days if it's clean title. I've got cash ready.", timestamp: 66 },
  { speaker: 'agent' as const, text: "That's great to hear. Can I add you to our buyer list so we can send deals that match your criteria?", timestamp: 74 },
  { speaker: 'buyer' as const, text: "Yeah absolutely. Email works better for me — send them over.", timestamp: 80 },
]
