// ─── CONTRACT PDF GENERATION ────────────────────────────────────────────────
// Converts rendered contract HTML into a PDF buffer. Uses Puppeteer if
// available, otherwise falls back to returning raw HTML as a downloadable
// buffer. Also exports a convenience function that chains the full pipeline:
// getTemplate → fillContract → renderHTML → generatePDF.

import { getTemplate } from './templates'
import { fillContract, type FillContractInput, type FilledContract } from './fill'
import { renderContractHTML, type RenderOptions } from './render'

export interface GenerateResult {
  html: string
  pdf: Buffer
  contentType: string // "application/pdf" or "text/html" for fallback
  filledData: Record<string, string>
  missingFields: string[]
}

/**
 * Convert an HTML string to a PDF buffer using Puppeteer.
 * Falls back to returning the HTML as a buffer if Puppeteer is not installed.
 */
const PDF_TIMEOUT_MS = 15_000

export async function generateContractPDF(html: string): Promise<{ buffer: Buffer; contentType: string }> {
  try {
    // Dynamic import — Puppeteer is an optional peer dependency
    const puppeteer = await import('puppeteer')

    const pdfPromise = (async () => {
      const browser = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox'],
      })

      try {
        const page = await browser.newPage()
        await page.setContent(html, { waitUntil: 'networkidle0' })

        const pdfBuffer = await page.pdf({
          format: 'Letter',
          margin: { top: '1in', right: '1in', bottom: '1in', left: '1in' },
          printBackground: true,
          displayHeaderFooter: true,
          headerTemplate: `
            <div style="font-size:8px;color:#999;width:100%;text-align:left;padding-left:1in;font-family:Arial,sans-serif;">
              ASSIGNMENT OF CONTRACT AGREEMENT
            </div>`,
          footerTemplate: `
            <div style="font-size:8px;color:#999;width:100%;display:flex;justify-content:space-between;padding:0 1in;font-family:Arial,sans-serif;">
              <span>Confidential — Generated by DealFlow AI</span>
              <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
            </div>`,
        })

        return { buffer: Buffer.from(pdfBuffer), contentType: 'application/pdf' }
      } finally {
        await browser.close()
      }
    })()

    const timeoutPromise = new Promise<never>((_, reject) =>
      setTimeout(() => reject(new Error('PDF generation timed out')), PDF_TIMEOUT_MS),
    )

    return await Promise.race([pdfPromise, timeoutPromise])
  } catch (err) {
    if (err instanceof Error && err.message === 'PDF generation timed out') {
      console.warn('[PDF] Generation timed out after 15s, returning HTML fallback')
    }
    // Puppeteer not available or timed out — return HTML as fallback
    return {
      buffer: Buffer.from(html, 'utf-8'),
      contentType: 'text/html',
    }
  }
}

/**
 * Full pipeline: template → fill → render → PDF in one call.
 */
export async function generateContractFromDeal(
  templateId: string,
  input: FillContractInput,
  renderOptions?: RenderOptions,
): Promise<GenerateResult> {
  const template = getTemplate(templateId)
  if (!template) {
    throw new Error(`Contract template "${templateId}" not found`)
  }

  const filled: FilledContract = fillContract(template, input)
  const html = renderContractHTML(filled, renderOptions)
  const { buffer, contentType } = await generateContractPDF(html)

  return {
    html,
    pdf: buffer,
    contentType,
    filledData: filled.filledData,
    missingFields: filled.missingFields,
  }
}
