// ─── CONTRACT PDF GENERATION ────────────────────────────────────────────────
// Converts rendered contract HTML into a PDF buffer. Returns HTML as a
// downloadable buffer (suitable for client-side print-to-PDF). Also exports
// a convenience function that chains the full pipeline:
// getTemplate → fillContract → renderHTML → generatePDF.

import { getTemplate } from './templates'
import { fillContract, type FillContractInput, type FilledContract } from './fill'
import { renderContractHTML, type RenderOptions } from './render'

export interface GenerateResult {
  html: string
  pdf: Buffer
  contentType: string
  filledData: Record<string, string>
  missingFields: string[]
}

/**
 * Generate a print-ready HTML buffer from a contract HTML string.
 * Includes embedded print styles so the browser's print dialog
 * produces a properly formatted PDF (letter size, 1-inch margins,
 * header/footer). No server-side dependencies required.
 */
export async function generateContractPDF(html: string): Promise<{ buffer: Buffer; contentType: string }> {
  const printHtml = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    @page {
      size: letter;
      margin: 1in;
    }
    @media print {
      body { margin: 0; font-family: 'Times New Roman', Times, serif; }
      .print-header { position: running(header); font-size: 8px; color: #999; }
      .print-footer { position: running(footer); font-size: 8px; color: #999; display: flex; justify-content: space-between; }
    }
    body { font-family: 'Times New Roman', Times, serif; line-height: 1.6; }
  </style>
</head>
<body>
  <div class="print-header">ASSIGNMENT OF CONTRACT AGREEMENT</div>
  ${html}
  <div class="print-footer">
    <span>Confidential — Generated by DealFlow AI</span>
  </div>
</body>
</html>`

  return {
    buffer: Buffer.from(printHtml, 'utf-8'),
    contentType: 'text/html',
  }
}

/**
 * Full pipeline: template → fill → render → PDF in one call.
 */
export async function generateContractFromDeal(
  templateId: string,
  input: FillContractInput,
  renderOptions?: RenderOptions,
): Promise<GenerateResult> {
  const template = getTemplate(templateId)
  if (!template) {
    throw new Error(`Contract template "${templateId}" not found`)
  }

  const filled: FilledContract = fillContract(template, input)
  const html = renderContractHTML(filled, renderOptions)
  const { buffer, contentType } = await generateContractPDF(html)

  return {
    html,
    pdf: buffer,
    contentType,
    filledData: filled.filledData,
    missingFields: filled.missingFields,
  }
}
