// ─── CONTRACT HTML RENDERER ─────────────────────────────────────────────────
// Produces a print-ready HTML document from a FilledContract. Designed for
// direct conversion to PDF — A4/Letter page size, professional typography,
// numbered sections, signature blocks, and optional DRAFT watermark.

import type { FilledContract } from './fill'

export interface RenderOptions {
  isDraft?: boolean
}

export function renderContractHTML(
  filled: FilledContract,
  options: RenderOptions = {},
): string {
  const { isDraft = false } = options

  const sectionsHTML = filled.filledSections
    .map((section, idx) => {
      const isSignatures = section.heading.toLowerCase() === 'signatures'
      const isFirstHeading = idx === 0

      // Preserve newlines in signature blocks
      const bodyHTML = isSignatures
        ? `<pre class="sig-block">${escapeHTML(section.body)}</pre>`
        : `<p>${highlightFilled(escapeHTML(section.body))}</p>`

      const pageBreak = idx > 0 && idx % 4 === 0 ? ' page-break' : ''

      return `
      <div class="section${pageBreak}">
        <h${isFirstHeading ? '1' : '2'}>${escapeHTML(section.heading)}${isFirstHeading ? '' : ''}</h${isFirstHeading ? '1' : '2'}>
        ${bodyHTML}
      </div>`
    })
    .join('\n')

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHTML(filled.templateName)}</title>
<style>
${CSS(isDraft)}
</style>
</head>
<body>
${isDraft ? '<div class="watermark">DRAFT</div>' : ''}
<div class="document">
  ${sectionsHTML}

  <div class="disclaimer">
    <p>This document was generated by DealFlow AI for reference purposes. Consult a licensed attorney in your state before executing.</p>
  </div>
</div>
</body>
</html>`
}

// ─── INTERNAL HELPERS ───────────────────────────────────────────────────────

function escapeHTML(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

/** Wraps filled-in values (anything that isn't a [placeholder]) with a span */
function highlightFilled(html: string): string {
  // Highlight bracket placeholders for missing fields
  return html.replace(
    /\[(\w+)\]/g,
    '<span class="missing">[$1]</span>',
  )
}

// ─── CSS ────────────────────────────────────────────────────────────────────

function CSS(isDraft: boolean): string {
  return `
  @page {
    size: letter;
    margin: 1in;
  }

  * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }

  body {
    font-family: Georgia, 'Times New Roman', Times, serif;
    font-size: 12pt;
    line-height: 1.5;
    color: #1a1a1a;
    background: #fff;
    position: relative;
  }

  .document {
    max-width: 8.5in;
    margin: 0 auto;
    padding: 0;
    position: relative;
  }

  /* ── Watermark ── */
  ${isDraft ? `
  .watermark {
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%) rotate(-45deg);
    font-size: 120pt;
    font-family: Arial, Helvetica, sans-serif;
    font-weight: bold;
    color: rgba(200, 200, 200, 0.25);
    letter-spacing: 0.15em;
    pointer-events: none;
    z-index: 0;
    white-space: nowrap;
  }` : ''}

  /* ── Header (running) ── */
  @media print {
    body::before {
      content: "ASSIGNMENT OF CONTRACT AGREEMENT";
      position: fixed;
      top: 0.35in;
      left: 1in;
      font-family: Arial, Helvetica, sans-serif;
      font-size: 8pt;
      color: #999;
      letter-spacing: 0.05em;
    }
  }

  /* ── Footer (running) ── */
  @media print {
    body::after {
      content: "Confidential — Generated by DealFlow AI";
      position: fixed;
      bottom: 0.35in;
      right: 1in;
      font-family: Arial, Helvetica, sans-serif;
      font-size: 8pt;
      color: #999;
    }
  }

  /* ── Sections ── */
  .section {
    margin-bottom: 1.25em;
    position: relative;
    z-index: 1;
  }

  .section.page-break {
    page-break-before: always;
  }

  h1 {
    font-size: 16pt;
    font-weight: bold;
    text-align: center;
    margin-bottom: 1em;
    text-transform: uppercase;
    letter-spacing: 0.04em;
    border-bottom: 2px solid #333;
    padding-bottom: 0.4em;
  }

  h2 {
    font-size: 12pt;
    font-weight: bold;
    margin-bottom: 0.5em;
    margin-top: 0.75em;
    text-transform: uppercase;
    letter-spacing: 0.02em;
  }

  p {
    margin-bottom: 0.75em;
    text-align: justify;
    text-indent: 0;
  }

  /* ── Filled value styling ── */
  .missing {
    color: #b91c1c;
    font-weight: bold;
    text-decoration: underline;
    text-decoration-style: wavy;
    text-decoration-color: #b91c1c;
  }

  /* ── Signature block ── */
  .sig-block {
    font-family: Georgia, 'Times New Roman', Times, serif;
    font-size: 12pt;
    line-height: 2.2;
    white-space: pre-wrap;
    margin-top: 1em;
    page-break-inside: avoid;
  }

  /* ── Disclaimer ── */
  .disclaimer {
    margin-top: 2em;
    padding-top: 1em;
    border-top: 1px solid #ccc;
    page-break-inside: avoid;
  }

  .disclaimer p {
    font-family: Arial, Helvetica, sans-serif;
    font-size: 9pt;
    color: #666;
    font-style: italic;
    text-align: center;
  }
`
}
